# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  secret_key_base: d5648cb5bb6cbe7d27fb5b748a635995b56ec6ad6e738cbb247c7b2b33af89580dec84a622e4e8150637070ffce04a1d76b6373ef559e6112fce509ecb775297
  qbo_app_consumer_key: <%= ENV['QBO_RAILS_CONSUMER_KEY'] || '111111' %>
  qbo_app_consumer_secret: <%= ENV['QBO_RAILS_CONSUMER_SECRET'] || '222222' %>
  qbo_sandbox_access_token: <%= ENV['QBO_RAILS_ACCESS_TOKEN'] || '3333333' %>
  qbo_sandbox_access_token_secret: <%= ENV['QBO_RAILS_ACCESS_TOKEN_SECRET'] || '444444' %>
  qbo_sandbox_company_id: <%= ENV['QBO_RAILS_COMPANY_ID'] || '5555555' %>

test:
  <<: *default
